export type Route =
  | 'projects'
  | 'overview'
  | 'setup'
  | 'live'
  | 'results'
  | 'issues'
  | 'links'
  | 'performance'
  | 'extractions'
  | 'schedules'
  | 'exports'
  | 'settings'
  | 'client-errors'
  | 'keywords'
  | 'content'
  | 'clusters'
